// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        print('******* - TG-Android');
        return android;
      case TargetPlatform.iOS:
        print('******* - TG-iOS');
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGCd4idhAaLVR2OYfF0-8Hcme9PUQ9Iwc',
    appId: '1:422285872338:web:bbb28a65a1481b7bdab10b',
    messagingSenderId: '422285872338',
    projectId: 'curso-flutter-tg',
    authDomain: 'curso-flutter-tg.firebaseapp.com',
    storageBucket: 'curso-flutter-tg.firebasestorage.app',
    measurementId: 'G-C1LWDVNTYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApI95X5YlZRZ8OlPe16vbEqh6Wx0SMPIE',
    appId: '1:422285872338:android:6366514b887c9971dab10b',
    messagingSenderId: '422285872338',
    projectId: 'curso-flutter-tg',
    storageBucket: 'curso-flutter-tg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6QeTHR9r8y-T5wHTUxhXhJ7Drm1lCWgo',
    appId: '1:422285872338:ios:40d06e822e914f58dab10b',
    messagingSenderId: '422285872338',
    projectId: 'curso-flutter-tg',
    storageBucket: 'curso-flutter-tg.firebasestorage.app',
    iosBundleId: 'com.example.ejercicio07',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6QeTHR9r8y-T5wHTUxhXhJ7Drm1lCWgo',
    appId: '1:422285872338:ios:40d06e822e914f58dab10b',
    messagingSenderId: '422285872338',
    projectId: 'curso-flutter-tg',
    storageBucket: 'curso-flutter-tg.firebasestorage.app',
    iosBundleId: 'com.example.ejercicio07',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGCd4idhAaLVR2OYfF0-8Hcme9PUQ9Iwc',
    appId: '1:422285872338:web:ab62be9fb7851372dab10b',
    messagingSenderId: '422285872338',
    projectId: 'curso-flutter-tg',
    authDomain: 'curso-flutter-tg.firebaseapp.com',
    storageBucket: 'curso-flutter-tg.firebasestorage.app',
    measurementId: 'G-NEHDEBD8BD',
  );
}
